# GitHub Actions workflow for automated deployment to GitHub Pages
# This workflow builds the React application and deploys it to GitHub Pages
# Triggered on push to main branch and manual workflow dispatch

name: Deploy to GitHub Pages

# Workflow triggers
on:
  # Trigger on push to main branch
  push:
    branches: [main]

  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job - compiles the React application
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      # Setup pnpm package manager
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      # Install project dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run linting to ensure code quality
      - name: Run ESLint
        run: pnpm run lint
        continue-on-error: true # Don't fail build on lint errors

      # Build the production application
      - name: Build application
        run: pnpm run build
        env:
          NODE_ENV: production

      # Setup GitHub Pages configuration
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload build artifacts for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deploy job - deploys the built application to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Notification job - sends deployment status (optional)
  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always() # Run regardless of previous job status

    steps:
      # Send success notification
      - name: Deployment Success
        if: needs.deploy.result == 'success'
        run: |
          echo "🎉 Deployment successful!"
          echo "Application is now live at: https://${{ github.repository_owner }}.github.io/BehaviorMonitor/"

      # Send failure notification
      - name: Deployment Failed
        if: needs.deploy.result == 'failure'
        run: |
          echo "❌ Deployment failed!"
          echo "Please check the workflow logs for details."
